services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "schedule"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - docker-network
    restart: always

  api-agenda:
    container_name: api-agenda
    image: agenda-aulas-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: qa
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge
