jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/schedule?currentSchema=public
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      format_sql: true

  flyway:
    repair-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
