jwt:
  public-key: classpath:app.pub
  private-key: classpath:app.key

spring:
  application:
    name: "agenda-aulas-api"

  config:
    activate:
      on-profile:
        - qa

  datasource:
    url: jdbc:postgresql://postgres-db:5432/schedule?currentSchema=public
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /agenda-api/swagger-ui.html


  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      flywaydb: DEBUG
    springframework:
      security: DEBUG
